import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from './src/theme/ThemeProvider'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full'>

      <body className={clsx(inter.className, "bg-background h-full")}>
        {children}
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem></ThemeProvider>
        <div className='flex flex-col h-full'></div>
      </body>
    </html>
  )
}
