import type { Metadata } from 'next'
import './globals.css'
import { ChakraProvider } from '@chakra-ui/react'
import { Provider } from 'react-redux';
//import { store } from '@/store/store'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

        <ChakraProvider>
          {children}
        </ChakraProvider>

      </body>
    </html>
  )
}
